### ISSUE TITLE
Install problem : api.compatibleWith

### ISSUE THREAD

**Issue by JohnDoe8521** [quasarframework/app-extension-qenv#2]
Hello,

I try to install this extension from quasar 1-beta18 but error : 

(node:99128) UnhandledPromiseRejectionWarning:   TypeError: api.compatibleWith is not a function

**Comment by nothingismagick** [comment]
this means that your version of @quasar/cli is outdated.
```
$ npm install -g @quasar/cli
$ quasar upgrade -i
```

**Comment by JohnDoe8521** [comment]
Many thanks, that works :)

**Comment by NicksonYap** [comment]
```
quasar upgrade -i
```

did the trick, had to be small letter "i"

**Comment by nothingismagick** [comment]
oops - my bad, sry
