### ISSUE TITLE
Use cross-env for cross platform when using 'QENV='

### ISSUE THREAD

**Issue by NicksonYap** [quasarframework/app-extension-qenv#3]
Hi,

I'm using Windows

I got this extension working by installing `cross-env`
https://www.npmjs.com/package/cross-env

```
npm install --save-dev cross-env
```

then in `package.json`

```
    "dev": "cross-env QENV=development quasar dev",
```

The following will now work on Windows

```
npm run dev
```

**Comment by hawkeye64** [comment]
Unfortunately I do not have windows, so much appreciated to have this information. I'll update the docs.

**Comment by hawkeye64** [comment]
Updated readme is live on github
