### ISSUE TITLE
qenv is deprecated

### ISSUE THREAD

**Issue by tomers** [quasarframework/app-extension-qenv#42]
Since qenv is apparently deprecated, see https://www.npmjs.com/package/qenv, I wonder why should we have this extension available, when we can use the more maintainer dotenv package using the https://github.com/quasarframework/app-extension-dotenv extension?

**Comment by hawkeye64** [comment]
@tomers Why would you say QEnv is deprecated?

**Comment by hawkeye64** [comment]
Also, with all due respect, you misunderstand the purpose between QEnv vs dotenv

**Comment by hawkeye64** [comment]
One more thing, this package is not dependent on the NPM package QEnv. This is stand-alone, which I wrote and it's full name is `app-extension-qenv`. I don't add the "q" if it's just a wrapper, like `app-extension-dotenv`.

**Comment by tomers** [comment]
@hawkeye64, yeah I guess I misunderstood the differences between dotenv and qenv.

As for deprecation, I thought this extension was a wrapper around the NPM package _qenv_, and I saw in [NPM](https://www.npmjs.com/package/qenv) the "This package has been deprecated" message. Sorry for the misunderstanding.

**Comment by hawkeye64** [comment]
@tomers It's ok. Caught me off-guard.

**Comment by tomers** [comment]
np. maybe consider adding a clarification in the readme. I may be no the only one who thought that it is a qenv wrapper

**Comment by hawkeye64** [comment]
I already removed it. Not sure how it got there. :(

**Comment by DarkLite1** [comment]
I would also like to know what the difference is between this extension and the [other one](https://github.com/quasarframework/app-extension-dotenv)? Maybe the README should be updated.

**Comment by hawkeye64** [comment]
@DarkLite1 agreed
