### ISSUE TITLE
qenv with heroku - doubt

### ISSUE THREAD

**Issue by eitalouarruda** [quasarframework/app-extension-qenv#55]
**Describe the doubt**
I guess its not a bug, but just I'm doing something wrong that I can't realize.

**To Reproduce**
I had qenv installed and everything works fine in dev env, (by the way amazing extension)
but when I pushed my app to heroku it can't read the ENV variables

This is my quasar.env.json:
<img width="821" alt="Screen Shot 2020-10-31 at 10 24 45" src="https://user-images.githubusercontent.com/8331926/97783083-4ea3c500-1b63-11eb-94f5-9a9a8e7ddd60.png">

the log on the app first page:
<img width="821" alt="Screen Shot 2020-10-31 at 10 25 08" src="https://user-images.githubusercontent.com/8331926/97783091-5bc0b400-1b63-11eb-9341-0566f43079c4.png">

the log result:
<img width="821" alt="Screen Shot 2020-10-31 at 10 30 08" src="https://user-images.githubusercontent.com/8331926/97783185-181a7a00-1b64-11eb-91e0-81cefd98452e.png">

the package.json:
<img width="821" alt="Screen Shot 2020-10-31 at 10 25 31" src="https://user-images.githubusercontent.com/8331926/97783095-68dda300-1b63-11eb-86d2-bdd05e5f4413.png">

Heroku vars:
<img width="821" alt="Screen Shot 2020-10-31 at 10 26 22" src="https://user-images.githubusercontent.com/8331926/97783115-8ad72580-1b63-11eb-82fc-238fec8da81d.png">
On heroku VAR I have setted the variables in two ways, just to test, but I guess the correct way will be API_URL and API_PORT

The quasar.env.json is in the git ignore file, so it is not commited on heroku, what I'm doing wrong here?

**Comment by hawkeye64** [comment]
@eitalouarruda Let me get this straight as I understand it:

You are using app-extension-qenv
You build for develop (quasar dev) and in the mounted it outputs to console your process.env.API_URL
You build for production (quasar build) and deploy your app to heroku, but it fails to print your process.env.API_URL and instead it prints undefined

I don't know about the heroku vars

What happens at build time is the qenv app-extension is injecting your vars to quasar.conf.js -> build -> env
These vars are then "baked" into your app, regardless of host and are always attached to `process.env`, which is hidden for security sake, so you must know the full var (ie: process.env.API_URL)
You can check if your build version is correct by using `quasar serve` to serve your production app
Open web browser at specified port, look at console and see if it printed in the mounted
If it did, and doesn't when under heroku, then there is an issue with the heruko platform in some way

**Comment by eitalouarruda** [comment]
Thank you so much, now I see my mistake.
The vars are "baked" in the app, so theres no way to the app read the heroku vars.
