### ISSUE TITLE
Cross-env not woking and cant access process variable in during boot

### ISSUE THREAD

**Issue by baramofme** [quasarframework/app-extension-qenv#61]
**Describe the bug**
Can't access process variable during boot process.

**To Reproduce**
1. Install Cross-env and give QENV option on npm scripts 
   `"web-run-local": "cross-env PROFILE=local quasar dev"`
2. Inside on of boot file, try  `console.log(process)`
3. there is nothing like that. error msg appear on console

```json
{
  "local": {
    "ENV_TYPE": "Running Development",
    "ENV_DEV": "Development",
    "HOST_URL": "http://someurl",
    "API_URL": "https://someurl",
    "SOCKET_URL": "https://someurl",
    "SOCKET_CHAT_PATH": "/chat/socket.io"
  },
```

**Expected behavior**
.quasar.env.json transformed js Object, And It's property merge into process.env object. (I know It's not node's process.env It's generated by quasar q-env)

and when, during boot process - browser phase - I can access process.env.HOST_URL, and get 'http://someurl" value.

But, can't even access process variable.

now I get hosturl using location.origin.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Additional context**

**Comment by hawkeye64** [comment]
@baramofme QEnv doesn't know to look at your PROFILE env var.
Try this:
```
"web-run-local": "cross-env QENV=local quasar dev"
```
