### ISSUE TITLE
Is it possible to change QENV at deployment/run time?

### ISSUE THREAD

**Issue by tanzencoder** [quasarframework/app-extension-qenv#62]
We have a need to change configuration depending on the environment that the application is deployed to. For example in our scenario we are deploying the application to a Kubernetes cluster using helm charts where we have the following clusters dev, qa, stage and prod. However we don't want to have to do a build for every environment, we would like to do one build but when we deploy the code to the next environment we just want to be able to set the QENV environment variable appropriately at deploy time. We have tried this on the container but it does not seem to be getting picked up. Is this even possible?

**Comment by hawkeye64** [comment]
@tanzencoder Sorry, there is no other way as the env vars get "baked" into your app. It's a build, not runtime feature.
However, I suppose if you had your own SSR server, you could "bake" in your env at runtime.
