### ISSUE TITLE
Missing QENV environment variable

### ISSUE THREAD

**Issue by rexdarelandig** [quasarframework/app-extension-qenv#64]
**Describe the bug**
Cannot build for electron

**To Reproduce**
1. Install quasar and qenv
2. Add necessary scripts for qenv
3. Develop in electron by running quasar dev -m electron

**Expected behavior**
It seems like it cannot find the variables. It works fine when run on browser using yarn dev. But compiling it to electro won't work.

**Screenshots**
This is the result when running quasar dev -m electron
![image](https://user-images.githubusercontent.com/57781286/107136454-43b8b780-693e-11eb-9602-16a04ea17072.png)

![image](https://user-images.githubusercontent.com/57781286/107136465-56cb8780-693e-11eb-8102-fdc663895325.png)

This is my package.json
![image](https://user-images.githubusercontent.com/57781286/107136470-62b74980-693e-11eb-8f04-be029c492570.png)

This is my .quasar.env.json
![image](https://user-images.githubusercontent.com/57781286/107136493-a3af5e00-693e-11eb-8f4c-ba4b16c05ead.png)

Everyting works fine on web but not on electron
![image](https://user-images.githubusercontent.com/57781286/107136508-d6595680-693e-11eb-9a36-10ea2e8987a5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Google Chrome (issue is for electron)

**Additional context**
I am building it on MacOS Catalina

**Comment by hawkeye64** [comment]
@rexdarelandig It appears it's not finding `QENV=development`.
I am not sure why it's not working for MacOS.
Anyway, you can also try the `cross-env` package, like this:
```
"dev": "cross-env QENV=development quasar dev"
```
Let me know how it goes

**Comment by rexdarelandig** [comment]
Still does not work 
@hawkeye64

**Comment by hawkeye64** [comment]
@rexdarelandig Can you show me the code you are using to access?

**Comment by rexdarelandig** [comment]
@hawkeye64 I am closing this since I was able to resolve the issue. the command  should not be
`quasar dev -m electron`
it should be
`yarn dev -m electron`

**Comment by hawkeye64** [comment]
@rexdarelandig Right you are. The script needs to be called. :)
