### ISSUE TITLE
Cant read `process.env.VAL` in production

### ISSUE THREAD

**Issue by jtlindsey** [quasarframework/app-extension-qenv#65]
**Describe the bug**
Server can't read `process.env` in production or the first time in development. Everything worked in development without this package just by using the more common `dotenv` package. After testing everything in dev mode and deploying/build to production `process.env` doesn't contain any of my custom variables. So i tried the suggested packages.

I'm trying to access `process.env.VAL` from inside `src-ssr/extensions.js` and it only works in development. 

I also checked the example in this repo but the example doesn't use `ssr`. The `src-ssr` is empty.

**To Reproduce**
1. Create a quasar app that is ssr (repo example [https://github.com/jtlindsey/quasar-broken-ssr-env](https://github.com/jtlindsey/quasar-broken-ssr-env))
2. Create some custom process.env variables like `VAL` in `.env` AND `.quasar.env.json`
3. See how process.env.VAL works fine in development Home page displays "Whatis val? something" `npm run dev`
4. See how in production it is undefined `npm run build && npm start`

**Expected behavior**
process.env.VAL should be available in production in `src-ssr`.

**Screenshots**

![Kapture 2021-03-27 at 07 20 56](https://user-images.githubusercontent.com/7409277/112719053-12378380-8ecd-11eb-9462-318620a7c954.gif)

**Platform (please complete the following information):**
`@quasar/app@2.2.2`
`quasar@1.15.6`
Quasar mode:

  - [ ] SPA
  - [x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac and Linux
Node: 14.16
NPM: 6.14.11
Browsers: All

**Additional context**
What is also strange is the behavior is not consistent or it doesn't work the first time in development.
1. start server with `npm run dev` an the example variable is undefined.
2. make small change on server `extension.js` file to trigger hot reload and see example variable is defined

Whatever is causing the above may be the reason why production never works.

Posting this in quasar too as it seems to be affecting more than just the env packages.
ref issue https://github.com/quasarframework/quasar/issues/8695

**Comment by hawkeye64** [comment]
@jtlindsey A couple of things:
1. Quasar obfuscates `process.env` for security purposes. You can `console.log(process.env.VAL)`, but you can't `console.log(process.env)`
2. The extension is only adding to the `build.env` inside your `quasar.conf.js`. I am not sure if those `process.env` variables are available `src-ssr/extensions.js`. The env vars are only made available to the client, not the server. If you need server, then use the regular dotenv server-side.

**Comment by jtlindsey** [comment]
@hawkeye64 

1. Understood. That is why i showed in the example being passed through to the client. Proof of what was going on is the same even if i remove console.log
2. The regular dotenv normally works in express.js apps without issue. It even works in development without this extension. I tried this extension and the other one for quasar (see example) because the docs outline how users are expected to use environment variables with quasar but don't address 1. the extensions only been tested for client side and 2. using dotenv the way i do in any other express app doesn't work when using quasar ssr and the docs don't account for this.

**Comment by hawkeye64** [comment]
@jtlindsey Understood. Will update the docs when I get some spare cycles.
