### ISSUE TITLE
Can we access process.env variables on quasar.conf.js?

### ISSUE THREAD

**Issue by chrislandeza** [quasarframework/app-extension-qenv#8]
I'm trying to access process.env variables on quasar.conf.js like this:
```
config: {
  brand: {
    primary: `${process.env.APP_PRIMARY_COLOR}`,
      secondary: '#26A69A',
      accent: '#9C27B0',
      positive: '#21BA45',
      negative: '#C10015',
      info: '#31CCEC',
      warning: '#F2C037'
    }
}
```
 but it's not working and  I'm getting 'undefined' on terminal console. 

APP_PRIMARY_COLOR has value when I logged it and view on the browser console:
![image](https://user-images.githubusercontent.com/4858242/62934952-7260db00-bdf8-11e9-927f-dfc2a8143766.png)

Did I missed something?

Here's my .quasar.env.json
```
{
  "dev": {
    "ENV_TYPE": "Running Development",
    "APP_PRIMARY_COLOR": "#25C4F2"
  },
  "prod": {
    "ENV_TYPE": "Running Production",
    "APP_PRIMARY_COLOR": "#41b883"
  },
  "nonprod": {
    "ENV_TYPE": "Running Non-Prod",
    "APP_PRIMARY_COLOR": "#FB503B"
  }
}
```

package.json
```
 "scripts": {
    "lint": "eslint --ext .js,.vue src",
    "test": "echo \"No test specified\" && exit 0",
    "dev": "cross-env QENV=dev quasar dev",
    "nonprod": "cross-env QENV=nonprod quasar build",
    "prod": "cross-env QENV=prod quasar build"
  },
```

Thanks

**Comment by chrislandeza** [comment]
My workaround to solve this is to parse `.quasar.env.json` file on

`quasar.conf.js`
```
// Configuration for your app
// https://quasar.dev/quasar-cli/quasar-conf-js
const fs = require('fs-extra')

// Environment Variables
let env = JSON.parse(fs.readFileSync('.quasar.env.json'))[process.env.QENV]
```

and use it like this:
```
 brand: {
    primary: env.APP_PRIMARY_COLOR,
    secondary: '#26A69A',
   ...
}
```

**Comment by hawkeye64** [comment]
My apologies. I somehow missed this issue. Thanks for the info. I can't see why your above code wouldn't work at all.
QEnv takes what it read and adds it to the `build.env` inside quasar.conf.js, once it has been read in. Webpack then puts this into data that is extracted as `process.env.whatever`.
I'll take a look as soon as I can get to it, but at least you found a work-around.

**Comment by hawkeye64** [comment]
So, no. You cannot access `process.env` from within `quasar.conf.js`. However, you can access everything that will be going into `process.env` -- use `build.env` from within `quasar.conf.js`. Everything in `build.env` will be converted to `process.env` (build-time, vs run-time).
